# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_learning_project"
version: "2.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - target
  - dbt_packages
  - logs

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_learning_project:
    marts:
      sales:
        +tags:
          - "hourly"
          - "finance"
          - "ETL"
      customers:
        +tags:
          - "daily"
          - "ETL"
  elementary:
    +schema: elementary

seeds:
  dbt_learning_project:
    zip_codes:
      schema: query_parameters
      config:
      +column_types:
        zip: string

tests:
  dbt_learning_project:
   +severity: warn

