with
    catalog_orders as (
        select              
                    cast('catalog_sales' as string) as `sale_channel`,
                    cast(`cs_sold_date_sk` as INT64) as `sold_date_sk` ,
                    cast(`cs_sold_time_sk` as INT64) as `sold_time_sk` ,
                    cast(`cs_ship_date_sk` as INT64) as `ship_date_sk` ,
                    cast(`cs_bill_customer_sk` as INT64) as `customer_sk` ,
                    cast(`cs_bill_cdemo_sk` as INT64) as `bill_cdemo_sk` ,
                    cast(`cs_bill_hdemo_sk` as INT64) as `bill_hdemo_sk` ,
                    cast(`cs_bill_addr_sk` as INT64) as `bill_addr_sk` ,
                    cast(`cs_ship_customer_sk` as INT64) as `ship_customer_sk` ,
                    cast(`cs_ship_cdemo_sk` as INT64) as `ship_cdemo_sk` ,
                    cast(`cs_ship_hdemo_sk` as INT64) as `ship_hdemo_sk` ,
                    cast(`cs_ship_addr_sk` as INT64) as `ship_addr_sk` ,
                    cast(`cs_call_center_sk` as INT64) as `call_center_sk` ,
                    cast(`cs_catalog_page_sk` as INT64) as `catalog_page_sk` ,
                    cast(`cs_ship_mode_sk` as INT64) as `ship_mode_sk` ,
                    cast(`cs_warehouse_sk` as INT64) as `warehouse_sk` ,
                    cast(`cs_item_sk` as INT64) as `item_sk` ,
                    cast(`cs_promo_sk` as INT64) as `promo_sk` ,
                    cast(`cs_order_number` as INT64) as `order_number` ,
                    cast(`cs_quantity` as INT64) as `quantity` ,
                    cast(`cs_wholesale_cost` as FLOAT64) as `wholesale_cost` ,
                    cast(`cs_list_price` as FLOAT64) as `list_price` ,
                    cast(`cs_sales_price` as FLOAT64) as `sales_price` ,
                    cast(`cs_ext_discount_amt` as FLOAT64) as `ext_discount_amt` ,
                    cast(`cs_ext_sales_price` as FLOAT64) as `ext_sales_price` ,
                    cast(`cs_ext_wholesale_cost` as FLOAT64) as `ext_wholesale_cost` ,
                    cast(`cs_ext_list_price` as FLOAT64) as `ext_list_price` ,
                    cast(`cs_ext_tax` as FLOAT64) as `ext_tax` ,
                    cast(`cs_coupon_amt` as FLOAT64) as `coupon_amt` ,
                    cast(`cs_ext_ship_cost` as FLOAT64) as `ext_ship_cost` ,
                    cast(`cs_net_paid` as FLOAT64) as `net_paid` ,
                    cast(`cs_net_paid_inc_tax` as FLOAT64) as `net_paid_inc_tax` ,
                    cast(`cs_net_paid_inc_ship` as FLOAT64) as `net_paid_inc_ship` ,
                    cast(`cs_net_paid_inc_ship_tax` as FLOAT64) as `net_paid_inc_ship_tax` ,
                    cast(`cs_net_profit` as FLOAT64) as `net_profit` ,
                    cast(null as INT64) as `web_page_sk` ,
                    cast(null as INT64) as `web_site_sk` ,
                    cast(null as INT64) as `cdemo_sk` ,
                    cast(null as INT64) as `hdemo_sk` ,
                    cast(null as INT64) as `addr_sk` ,
                    cast(null as INT64) as `store_sk` ,
                    cast(null as INT64) as `ticket_number` 
        from {{ ref("stg_tpcds__catalog_sales") }}

    ),
    web_orders as (
        select
               
                    cast('web_sales'  as STRING) as `sale_channel` ,
                    cast(`ws_sold_date_sk` as INT64) as `sold_date_sk` ,
                    cast(`ws_sold_time_sk` as INT64) as `sold_time_sk` ,
                    cast(`ws_ship_date_sk` as INT64) as `ship_date_sk` ,
                    cast(`ws_bill_customer_sk` as INT64) as `customer_sk` ,
                    cast(`ws_bill_cdemo_sk` as INT64) as `bill_cdemo_sk` ,
                    cast(`ws_bill_hdemo_sk` as INT64) as `bill_hdemo_sk` ,
                    cast(`ws_bill_addr_sk` as INT64) as `bill_addr_sk` ,
                    cast(`ws_ship_customer_sk` as INT64) as `ship_customer_sk` ,
                    cast(`ws_ship_cdemo_sk` as INT64) as `ship_cdemo_sk` ,
                    cast(`ws_ship_hdemo_sk` as INT64) as `ship_hdemo_sk` ,
                    cast(`ws_ship_addr_sk` as INT64) as `ship_addr_sk` ,
                    cast(null as INT64) as `call_center_sk` ,
                    cast(null as INT64) as `catalog_page_sk` ,
                    cast(`ws_ship_mode_sk` as INT64) as `ship_mode_sk` ,
                    cast(`ws_warehouse_sk` as INT64) as `warehouse_sk` ,
                    cast(`ws_item_sk` as INT64) as `item_sk` ,
                    cast(`ws_promo_sk` as INT64) as `promo_sk` ,
                    cast(`ws_order_number` as INT64) as `order_number` ,
                    cast(`ws_quantity` as INT64) as `quantity` ,
                    cast(`ws_wholesale_cost` as FLOAT64) as `wholesale_cost` ,
                    cast(`ws_list_price` as FLOAT64) as `list_price` ,
                    cast(`ws_sales_price` as FLOAT64) as `sales_price` ,
                    cast(`ws_ext_discount_amt` as FLOAT64) as `ext_discount_amt` ,
                    cast(`ws_ext_sales_price` as FLOAT64) as `ext_sales_price` ,
                    cast(`ws_ext_wholesale_cost` as FLOAT64) as `ext_wholesale_cost` ,
                    cast(`ws_ext_list_price` as FLOAT64) as `ext_list_price` ,
                    cast(`ws_ext_tax` as FLOAT64) as `ext_tax` ,
                    cast(`ws_coupon_amt` as FLOAT64) as `coupon_amt` ,
                    cast(`ws_ext_ship_cost` as FLOAT64) as `ext_ship_cost` ,
                    cast(`ws_net_paid` as FLOAT64) as `net_paid` ,
                    cast(`ws_net_paid_inc_tax` as FLOAT64) as `net_paid_inc_tax` ,
                    cast(`ws_net_paid_inc_ship` as FLOAT64) as `net_paid_inc_ship` ,
                    cast(`ws_net_paid_inc_ship_tax` as FLOAT64) as `net_paid_inc_ship_tax` ,
                    cast(`ws_net_profit` as FLOAT64) as `net_profit` ,
                    cast(`ws_web_page_sk` as INT64) as `web_page_sk` ,
                    cast(`ws_web_site_sk` as INT64) as `web_site_sk` ,
                    cast(null as INT64) as `cdemo_sk` ,
                    cast(null as INT64) as `hdemo_sk` ,
                    cast(null as INT64) as `addr_sk` ,
                    cast(null as INT64) as `store_sk` ,
                    cast(null as INT64) as `ticket_number` 
        from {{ ref("stg_tpcds__web_sales") }}
    ),
    store_orders as (
        select
                    cast('store_sales' as STRING) as `sale_channel` ,
                    cast(`ss_sold_date_sk` as INT64) as `sold_date_sk` ,
                    cast(`ss_sold_time_sk` as INT64) as `sold_time_sk` ,
                    cast(null as INT64) as `ship_date_sk` ,
                    cast(`ss_customer_sk` as INT64) as `customer_sk` ,
                    cast(null as INT64) as `bill_cdemo_sk` ,
                    cast(null as INT64) as `bill_hdemo_sk` ,
                    cast(null as INT64) as `bill_addr_sk` ,
                    cast(null as INT64) as `ship_customer_sk` ,
                    cast(null as INT64) as `ship_cdemo_sk` ,
                    cast(null as INT64) as `ship_hdemo_sk` ,
                    cast(null as INT64) as `ship_addr_sk` ,
                    cast(null as INT64) as `call_center_sk` ,
                    cast(null as INT64) as `catalog_page_sk` ,
                    cast(null as INT64) as `ship_mode_sk` ,
                    cast(null as INT64) as `warehouse_sk` ,
                    cast(`ss_item_sk` as INT64) as `item_sk` ,
                    cast(`ss_promo_sk` as INT64) as `promo_sk` ,
                    cast(null as INT64) as `order_number` ,
                    cast(`ss_quantity` as INT64) as `quantity` ,
                    cast(`ss_wholesale_cost` as FLOAT64) as `wholesale_cost` ,
                    cast(`ss_list_price` as FLOAT64) as `list_price` ,
                    cast(`ss_sales_price` as FLOAT64) as `sales_price` ,
                    cast(`ss_ext_discount_amt` as FLOAT64) as `ext_discount_amt` ,
                    cast(`ss_ext_sales_price` as FLOAT64) as `ext_sales_price` ,
                    cast(`ss_ext_wholesale_cost` as FLOAT64) as `ext_wholesale_cost` ,
                    cast(`ss_ext_list_price` as FLOAT64) as `ext_list_price` ,
                    cast(`ss_ext_tax` as FLOAT64) as `ext_tax` ,
                    cast(`ss_coupon_amt` as FLOAT64) as `coupon_amt` ,
                    cast(null as FLOAT64) as `ext_ship_cost` ,
                    cast(`ss_net_paid` as FLOAT64) as `net_paid` ,
                    cast(`ss_net_paid_inc_tax` as FLOAT64) as `net_paid_inc_tax` ,
                    cast(null as FLOAT64) as `net_paid_inc_ship` ,
                    cast(null as FLOAT64) as `net_paid_inc_ship_tax` ,
                    cast(`ss_net_profit` as FLOAT64) as `net_profit` ,
                    cast(null as INT64) as `web_page_sk` ,
                    cast(null as INT64) as `web_site_sk` ,
                    cast(`ss_cdemo_sk` as INT64) as `cdemo_sk` ,
                    cast(`ss_hdemo_sk` as INT64) as `hdemo_sk` ,
                    cast(`ss_addr_sk` as INT64) as `addr_sk` ,
                    cast(`ss_store_sk` as INT64) as `store_sk` ,
                    cast(`ss_ticket_number` as INT64) as `ticket_number`

        from {{ ref("stg_tpcds__store_sales") }}
    )

select *
from catalog_orders
union all
select *
from web_orders
union all
select *
from store_orders
